# Generated by Django 4.0.3 on 2022-03-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_picture/default_profile.jpg', upload_to='profile_picture'),
        ),
    ]
