# Generated by Django 4.0.3 on 2022-03-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posed_at',
            new_name='posted_at',
        ),
    ]
